spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jdbc
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  application:
    name: jdbc

logging:
  level:
    org.hibernate.SQL: debug